name: restaurante
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: 'assets/icon.ico'
  

flutter:
  uses-material-design: true

  assets: 
    - assets/burger.png
    - assets/domicilio.png
    - assets/menu1.png
    - assets/menu2.png
    - assets/moto.png
    - assets/domicilios.png
    - assets/sedes.png
    - assets/carrito.png
    - assets/cargar.png
    - assets/registro.png
    - assets/cupones.png
    - assets/creado.png
    - assets/poblado.png
    - assets/belen.png

    
    